# Generated by Django 4.0.5 on 2022-06-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePhoto',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
