# Generated by Django 4.0.5 on 2022-06-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cart_user_alter_cart_id_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
